### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by iShafayet** [a1626/generator-polymer-init-cordova-2.x#1]
Getting a blank screen in the emulator. Getting this message in the console using `chrome://inspect/#devices` - 

```
file:///android_asset/www/bower_components/webcomponentsjs/webcomponents-loader.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///src/my-app.html Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by a1626** [comment]
Can you please post steps to reproduce the issue.

**Comment by a1626** [comment]
@iShafayet is this issue still occurring for you?

**Comment by iShafayet** [comment]
As of December 05, the project directory is successfully created. I think we can close this issue.
